package com.shiv.erp.controller;

import com.shiv.erp.model.AutomationEvent;
import com.shiv.erp.repository.AutomationEventRepository;
import com.shiv.erp.repository.ProductRepository;
import com.shiv.erp.repository.PurchaseOrderRepository;
import com.shiv.erp.repository.ManufacturingOrderRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.*;

@RestController
@RequestMapping("/api/automation")
public class AutomationController {

    private final AutomationEventRepository automationEventRepository;
    private final ProductRepository productRepository;
    private final PurchaseOrderRepository purchaseOrderRepository;
    private final ManufacturingOrderRepository manufacturingOrderRepository;

    public AutomationController(AutomationEventRepository automationEventRepository,
                                ProductRepository productRepository,
                                PurchaseOrderRepository purchaseOrderRepository,
                                ManufacturingOrderRepository manufacturingOrderRepository) {
        this.automationEventRepository = automationEventRepository;
        this.productRepository = productRepository;
        this.purchaseOrderRepository = purchaseOrderRepository;
        this.manufacturingOrderRepository = manufacturingOrderRepository;
    }

    @GetMapping("/summary")
    public ResponseEntity<Map<String, Object>> getSummary() {
        long activeShortages = productRepository.countActiveShortages();
        long autoGeneratedPOs = purchaseOrderRepository.countByIsAutoGeneratedTrue();
        long autoGeneratedMOs = manufacturingOrderRepository.countByIsAutoGeneratedTrue();
        long preventedStockouts = automationEventRepository.countSuccessful();
        long failed = automationEventRepository.countFailed();
        long total = preventedStockouts + failed;

        double successRate = 100.0;
        if (total > 0) {
            successRate = ((double) preventedStockouts / total) * 100.0;
        }

        Map<String, Object> summary = new HashMap<>();
        summary.put("activeShortages", activeShortages);
        summary.put("autoGeneratedPOs", autoGeneratedPOs);
        summary.put("autoGeneratedMOs", autoGeneratedMOs);
        summary.put("preventedStockouts", preventedStockouts);
        summary.put("successRate", Math.round(successRate * 10.0) / 10.0); // round to 1 decimal place

        return ResponseEntity.ok(summary);
    }

    @GetMapping("/events")
    public ResponseEntity<Page<AutomationEvent>> getEvents(
            @RequestParam(defaultValue = "1") int page,
            @RequestParam(defaultValue = "20") int size
    ) {
        Pageable pageable = PageRequest.of(Math.max(0, page - 1), size);
        return ResponseEntity.ok(automationEventRepository.findAllByOrderByTsDesc(pageable));
    }

    @GetMapping("/events/{id}/chain")
    public ResponseEntity<List<AutomationEvent>> getEventChain(@PathVariable String id) {
        Optional<AutomationEvent> rootOpt = automationEventRepository.findById(id);
        if (rootOpt.isEmpty()) {
            return ResponseEntity.notFound().build();
        }

        List<AutomationEvent> chain = new ArrayList<>();
        // Find absolute root of the chain if this is a sub-event
        AutomationEvent current = rootOpt.get();
        while (current.getParentEventId() != null) {
            Optional<AutomationEvent> parentOpt = automationEventRepository.findById(current.getParentEventId());
            if (parentOpt.isPresent()) {
                current = parentOpt.get();
            } else {
                break;
            }
        }

        traverseChain(current, chain);
        return ResponseEntity.ok(chain);
    }

    private void traverseChain(AutomationEvent event, List<AutomationEvent> chain) {
        chain.add(event);
        List<AutomationEvent> children = automationEventRepository.findByParentEventIdOrderByTsAsc(event.getId());
        for (AutomationEvent child : children) {
            traverseChain(child, chain);
        }
    }
}
