/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppPurchaseRouteImport } from './routes/_app.purchase'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppManufacturingRouteImport } from './routes/_app.manufacturing'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBomRouteImport } from './routes/_app.bom'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppSalesIndexRouteImport } from './routes/_app.sales.index'
import { Route as AppPurchaseIndexRouteImport } from './routes/_app.purchase.index'
import { Route as AppManufacturingIndexRouteImport } from './routes/_app.manufacturing.index'
import { Route as AppSalesIdRouteImport } from './routes/_app.sales.$id'
import { Route as AppPurchaseIdRouteImport } from './routes/_app.purchase.$id'
import { Route as AppManufacturingIdRouteImport } from './routes/_app.manufacturing.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseRoute = AppPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppManufacturingRoute = AppManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBomRoute = AppBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppPurchaseIndexRoute = AppPurchaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPurchaseRoute,
} as any)
const AppManufacturingIndexRoute = AppManufacturingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppManufacturingRoute,
} as any)
const AppSalesIdRoute = AppSalesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppPurchaseIdRoute = AppPurchaseIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPurchaseRoute,
} as any)
const AppManufacturingIdRoute = AppManufacturingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppManufacturingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/bom': typeof AppBomRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/manufacturing': typeof AppManufacturingRouteWithChildren
  '/products': typeof AppProductsRoute
  '/purchase': typeof AppPurchaseRouteWithChildren
  '/sales': typeof AppSalesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/manufacturing/$id': typeof AppManufacturingIdRoute
  '/purchase/$id': typeof AppPurchaseIdRoute
  '/sales/$id': typeof AppSalesIdRoute
  '/manufacturing/': typeof AppManufacturingIndexRoute
  '/purchase/': typeof AppPurchaseIndexRoute
  '/sales/': typeof AppSalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/bom': typeof AppBomRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/products': typeof AppProductsRoute
  '/settings': typeof AppSettingsRoute
  '/manufacturing/$id': typeof AppManufacturingIdRoute
  '/purchase/$id': typeof AppPurchaseIdRoute
  '/sales/$id': typeof AppSalesIdRoute
  '/manufacturing': typeof AppManufacturingIndexRoute
  '/purchase': typeof AppPurchaseIndexRoute
  '/sales': typeof AppSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/bom': typeof AppBomRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/manufacturing': typeof AppManufacturingRouteWithChildren
  '/_app/products': typeof AppProductsRoute
  '/_app/purchase': typeof AppPurchaseRouteWithChildren
  '/_app/sales': typeof AppSalesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/manufacturing/$id': typeof AppManufacturingIdRoute
  '/_app/purchase/$id': typeof AppPurchaseIdRoute
  '/_app/sales/$id': typeof AppSalesIdRoute
  '/_app/manufacturing/': typeof AppManufacturingIndexRoute
  '/_app/purchase/': typeof AppPurchaseIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/bom'
    | '/dashboard'
    | '/inventory'
    | '/manufacturing'
    | '/products'
    | '/purchase'
    | '/sales'
    | '/settings'
    | '/manufacturing/$id'
    | '/purchase/$id'
    | '/sales/$id'
    | '/manufacturing/'
    | '/purchase/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit'
    | '/bom'
    | '/dashboard'
    | '/inventory'
    | '/products'
    | '/settings'
    | '/manufacturing/$id'
    | '/purchase/$id'
    | '/sales/$id'
    | '/manufacturing'
    | '/purchase'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/bom'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/manufacturing'
    | '/_app/products'
    | '/_app/purchase'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/manufacturing/$id'
    | '/_app/purchase/$id'
    | '/_app/sales/$id'
    | '/_app/manufacturing/'
    | '/_app/purchase/'
    | '/_app/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase': {
      id: '/_app/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof AppPurchaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manufacturing': {
      id: '/_app/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof AppManufacturingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bom': {
      id: '/_app/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof AppBomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/purchase/': {
      id: '/_app/purchase/'
      path: '/'
      fullPath: '/purchase/'
      preLoaderRoute: typeof AppPurchaseIndexRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/manufacturing/': {
      id: '/_app/manufacturing/'
      path: '/'
      fullPath: '/manufacturing/'
      preLoaderRoute: typeof AppManufacturingIndexRouteImport
      parentRoute: typeof AppManufacturingRoute
    }
    '/_app/sales/$id': {
      id: '/_app/sales/$id'
      path: '/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof AppSalesIdRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/purchase/$id': {
      id: '/_app/purchase/$id'
      path: '/$id'
      fullPath: '/purchase/$id'
      preLoaderRoute: typeof AppPurchaseIdRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/manufacturing/$id': {
      id: '/_app/manufacturing/$id'
      path: '/$id'
      fullPath: '/manufacturing/$id'
      preLoaderRoute: typeof AppManufacturingIdRouteImport
      parentRoute: typeof AppManufacturingRoute
    }
  }
}

interface AppManufacturingRouteChildren {
  AppManufacturingIdRoute: typeof AppManufacturingIdRoute
  AppManufacturingIndexRoute: typeof AppManufacturingIndexRoute
}

const AppManufacturingRouteChildren: AppManufacturingRouteChildren = {
  AppManufacturingIdRoute: AppManufacturingIdRoute,
  AppManufacturingIndexRoute: AppManufacturingIndexRoute,
}

const AppManufacturingRouteWithChildren =
  AppManufacturingRoute._addFileChildren(AppManufacturingRouteChildren)

interface AppPurchaseRouteChildren {
  AppPurchaseIdRoute: typeof AppPurchaseIdRoute
  AppPurchaseIndexRoute: typeof AppPurchaseIndexRoute
}

const AppPurchaseRouteChildren: AppPurchaseRouteChildren = {
  AppPurchaseIdRoute: AppPurchaseIdRoute,
  AppPurchaseIndexRoute: AppPurchaseIndexRoute,
}

const AppPurchaseRouteWithChildren = AppPurchaseRoute._addFileChildren(
  AppPurchaseRouteChildren,
)

interface AppSalesRouteChildren {
  AppSalesIdRoute: typeof AppSalesIdRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
}

const AppSalesRouteChildren: AppSalesRouteChildren = {
  AppSalesIdRoute: AppSalesIdRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
}

const AppSalesRouteWithChildren = AppSalesRoute._addFileChildren(
  AppSalesRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppBomRoute: typeof AppBomRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppManufacturingRoute: typeof AppManufacturingRouteWithChildren
  AppProductsRoute: typeof AppProductsRoute
  AppPurchaseRoute: typeof AppPurchaseRouteWithChildren
  AppSalesRoute: typeof AppSalesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppBomRoute: AppBomRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppManufacturingRoute: AppManufacturingRouteWithChildren,
  AppProductsRoute: AppProductsRoute,
  AppPurchaseRoute: AppPurchaseRouteWithChildren,
  AppSalesRoute: AppSalesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
