package com.shiv.erp.service;

import com.shiv.erp.model.*;
import com.shiv.erp.repository.*;
import com.shiv.erp.utils.SecurityUtils;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Service
public class ManufacturingOrderService {

    private final ManufacturingOrderRepository manufacturingOrderRepository;
    private final ProductRepository productRepository;
    private final BoMRepository bomRepository;
    private final StockLedgerService stockLedgerService;
    private final ProcurementService procurementService;
    private final AuditLogService auditLogService;
    private final WorkOrderRepository workOrderRepository;
    private final NotificationService notificationService;
    private final SalesOrderRepository salesOrderRepository;
    private final ShortageTicketRepository shortageTicketRepository;

    public ManufacturingOrderService(ManufacturingOrderRepository manufacturingOrderRepository,
                                     ProductRepository productRepository,
                                     BoMRepository bomRepository,
                                     StockLedgerService stockLedgerService,
                                     ProcurementService procurementService,
                                     AuditLogService auditLogService,
                                     WorkOrderRepository workOrderRepository,
                                     NotificationService notificationService,
                                     SalesOrderRepository salesOrderRepository,
                                     ShortageTicketRepository shortageTicketRepository) {
        this.manufacturingOrderRepository = manufacturingOrderRepository;
        this.productRepository = productRepository;
        this.bomRepository = bomRepository;
        this.stockLedgerService = stockLedgerService;
        this.procurementService = procurementService;
        this.auditLogService = auditLogService;
        this.workOrderRepository = workOrderRepository;
        this.notificationService = notificationService;
        this.salesOrderRepository = salesOrderRepository;
        this.shortageTicketRepository = shortageTicketRepository;
    }

    @Transactional
    public ManufacturingOrder createOrder(ManufacturingOrder draft) {
        String moId = "mo-" + UUID.randomUUID().toString().substring(0, 8);
        String number = procurementService.generateNextNumber("MO", manufacturingOrderRepository.findFirstByOrderByNumberDesc().map(ManufacturingOrder::getNumber));

        draft.setId(moId);
        draft.setNumber(number);
        draft.setStatus("Draft");
        draft.setIsAutoGenerated(false);

        // Fetch product & BOM to snapshot components and operations if they are not already provided
        if (draft.getComponents() == null || draft.getComponents().isEmpty() ||
            draft.getWorkOrders() == null || draft.getWorkOrders().isEmpty()) {

            BoM bom = bomRepository.findByProductIdAndIsActiveTrue(draft.getProductId()).orElse(null);
            if (bom != null) {
                if (draft.getComponents() == null || draft.getComponents().isEmpty()) {
                    List<MoComponent> moComponents = new ArrayList<>();
                    for (BomComponent bc : bom.getComponents()) {
                        int reqQty = (int) (bc.getQty() * draft.getQty());
                        moComponents.add(MoComponent.builder()
                                .moId(moId)
                                .productId(bc.getProductId())
                                .requiredQty(reqQty)
                                .toConsumeQty(reqQty)
                                .consumedQty(0)
                                .build());
                    }
                    draft.setComponents(moComponents);
                }

                if (draft.getWorkOrders() == null || draft.getWorkOrders().isEmpty()) {
                    List<WorkOrder> workOrders = new ArrayList<>();
                    for (BomOperation bo : bom.getOperations()) {
                        workOrders.add(WorkOrder.builder()
                                .id("wo-" + UUID.randomUUID().toString().substring(0, 8))
                                .moId(moId)
                                .name(bo.getName())
                                .workCenterId(bo.getWorkCenterId())
                                .status("Pending")
                                .expectedDurationMinutes(bo.getDurationMinutes())
                                .actualDurationMinutes(0)
                                .build());
                    }
                    draft.setWorkOrders(workOrders);
                }
            } else {
                draft.setComponents(new ArrayList<>());
                draft.setWorkOrders(new ArrayList<>());
            }
        } else {
            // Setup keys on provided lists
            for (MoComponent comp : draft.getComponents()) {
                comp.setMoId(moId);
                if (comp.getConsumedQty() == null) comp.setConsumedQty(0);
            }
            for (WorkOrder wo : draft.getWorkOrders()) {
                if (wo.getId() == null || wo.getId().isEmpty()) {
                    wo.setId("wo-" + UUID.randomUUID().toString().substring(0, 8));
                }
                wo.setMoId(moId);
                wo.setStatus("Pending");
                if (wo.getActualDurationMinutes() == null) wo.setActualDurationMinutes(0);
            }
        }

        ManufacturingOrder saved = manufacturingOrderRepository.save(draft);

        auditLogService.logChange(
                SecurityUtils.getCurrentUserId(),
                "ManufacturingOrder",
                saved.getId(),
                "Created",
                null,
                String.format("{\"number\": \"%s\", \"productId\": \"%s\"}", saved.getNumber(), saved.getProductId())
        );

        return saved;
    }

    @Transactional
    public ManufacturingOrder updateOrder(String id, ManufacturingOrder patch) {
        ManufacturingOrder mo = manufacturingOrderRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Manufacturing order not found: " + id));

        if (!"Draft".equals(mo.getStatus())) {
            throw new IllegalStateException("Only Draft manufacturing orders can be edited.");
        }

        if (patch.getAssigneeId() != null) {
            mo.setAssigneeId(patch.getAssigneeId().isEmpty() ? null : patch.getAssigneeId());
        }
        if (patch.getQty() != null) {
            mo.setQty(patch.getQty());
        }

        if (patch.getComponents() != null) {
            mo.getComponents().clear();
            for (MoComponent comp : patch.getComponents()) {
                comp.setMoId(id);
                if (comp.getRequiredQty() == null) {
                    comp.setRequiredQty(0);
                }
                if (comp.getToConsumeQty() == null) {
                    comp.setToConsumeQty(comp.getRequiredQty());
                }
                if (comp.getConsumedQty() == null) {
                    comp.setConsumedQty(0);
                }
                mo.getComponents().add(comp);
            }
        }

        return manufacturingOrderRepository.save(mo);
    }

    @Transactional
    public ManufacturingOrder confirmOrder(String id) {
        ManufacturingOrder mo = manufacturingOrderRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Manufacturing order not found: " + id));

        if (!"Draft".equals(mo.getStatus())) {
            throw new IllegalStateException("Only Draft manufacturing orders can be confirmed.");
        }

        String userId = SecurityUtils.getCurrentUserId();
        boolean waitingForMaterials = false;

        // Reserve component stock and check real availability
        if (mo.getComponents() != null) {
            for (MoComponent comp : mo.getComponents()) {
                Product compProduct = productRepository.findById(comp.getProductId()).orElse(null);
                if (compProduct != null) {
                    int freeToUse = compProduct.getOnHandQty() - compProduct.getReservedQty();
                    int required = comp.getRequiredQty();
                    if (freeToUse < required) {
                        waitingForMaterials = true;
                        int shortageQty = required - Math.max(0, freeToUse);
                        
                        String poId = null;
                        String poNumber = null;
                        try {
                            AutomationEvent ae = procurementService.triggerProcurementInternal(
                                    compProduct,
                                    shortageQty,
                                    mo.getTriggeringSalesOrderId(),
                                    "MO_SHORTAGE",
                                    mo.getId(),
                                    null,
                                    new java.util.HashSet<>(),
                                    0
                            );
                            if (ae != null) {
                                poId = ae.getGeneratedDocId();
                                poNumber = ae.getGeneratedDocNumber();
                            }
                        } catch (Exception e) {
                            // log error
                        }
                        
                        ShortageTicket ticket = ShortageTicket.builder()
                                .id("st-" + UUID.randomUUID().toString().substring(0, 8))
                                .moId(mo.getId())
                                .productId(comp.getProductId())
                                .shortageQty(shortageQty)
                                .poId(poId)
                                .poNumber(poNumber)
                                .status("OPEN")
                                .build();
                        shortageTicketRepository.save(ticket);
                    }
                }

                stockLedgerService.recordMovement(
                        comp.getProductId(),
                        "MFG_RESERVE",
                        comp.getRequiredQty(),
                        "MO",
                        mo.getId(),
                        "Reserve stock for Manufacturing Order"
                );
            }
        }

        String newStatus = waitingForMaterials ? "Waiting for Materials" : "Confirmed";
        mo.setStatus(newStatus);
        ManufacturingOrder saved = manufacturingOrderRepository.save(mo);

        auditLogService.logChange(
                userId,
                "ManufacturingOrder",
                saved.getId(),
                waitingForMaterials ? "Waiting for Materials" : "Confirmed",
                "Draft",
                newStatus
        );

        if (waitingForMaterials) {
            notificationService.notifyUserOrRoles(
                    saved.getAssigneeId(),
                    List.of("manufacturing", "admin"),
                    "MO Waiting for Materials",
                    String.format("Manufacturing Order %s is blocked: one or more components are insufficient. It will unblock automatically when stock is received.", saved.getNumber()),
                    "MANUFACTURING_ORDER",
                    saved.getId()
            );
        }

        return saved;
    }

    @Transactional
    public ManufacturingOrder setWorkOrderStatus(String moId, String woId, String status, String operatorId) {
        ManufacturingOrder mo = manufacturingOrderRepository.findById(moId)
                .orElseThrow(() -> new IllegalArgumentException("Manufacturing order not found: " + moId));

        WorkOrder targetWo = null;
        if (mo.getWorkOrders() != null) {
            for (WorkOrder wo : mo.getWorkOrders()) {
                if (wo.getId().equals(woId)) {
                    targetWo = wo;
                    break;
                }
            }
        }

        if (targetWo == null) {
            throw new IllegalArgumentException("Work Order not found: " + woId);
        }

        LocalDateTime now = LocalDateTime.now();
        String oldStatus = targetWo.getStatus();

        // Manage durations
        if ("Started".equals(oldStatus) && targetWo.getStartedAt() != null) {
            long minutes = Duration.between(targetWo.getStartedAt(), now).toMinutes();
            targetWo.setActualDurationMinutes(targetWo.getActualDurationMinutes() + (int) minutes);
        }

        targetWo.setStatus(status);
        if (operatorId != null) {
            targetWo.setOperatorId(operatorId);
        } else {
            targetWo.setOperatorId(SecurityUtils.getCurrentUserId());
        }

        if (!status.equals(oldStatus)) {
            Product product = productRepository.findById(mo.getProductId()).orElse(null);
            String productName = product != null ? product.getName() : mo.getProductId();

            auditLogService.logChange(
                    operatorId != null ? operatorId : SecurityUtils.getCurrentUserId(),
                    "WorkOrder",
                    targetWo.getId(),
                    "StatusChanged",
                    oldStatus,
                    String.format("{\"newStatus\": \"%s\", \"moId\": \"%s\", \"moNumber\": \"%s\", \"productName\": \"%s\"}", status, mo.getId(), mo.getNumber(), productName)
            );
        }

        if ("Started".equals(status)) {
            targetWo.setStartedAt(now);
            targetWo.setPausedAt(null);
        } else if ("Paused".equals(status)) {
            targetWo.setStartedAt(null);
            targetWo.setPausedAt(now);
        } else if ("Completed".equals(status)) {
            targetWo.setStartedAt(null);
            targetWo.setCompletedAt(now);
        }

        // Auto transition MO to In Progress if it is Confirmed or Waiting for Materials and any work order is Started/Paused/Completed
        if ("Confirmed".equals(mo.getStatus()) || "Waiting for Materials".equals(mo.getStatus())) {
            String oldMoStatus = mo.getStatus();
            mo.setStatus("In Progress");
            Product product = productRepository.findById(mo.getProductId()).orElse(null);
            String productName = product != null ? product.getName() : mo.getProductId();

            auditLogService.logChange(
                    SecurityUtils.getCurrentUserId(),
                    "ManufacturingOrder",
                    mo.getId(),
                    "StatusChanged",
                    oldMoStatus,
                    String.format("{\"newStatus\": \"%s\", \"productName\": \"%s\"}", "In Progress", productName)
            );
        }

        ManufacturingOrder saved = manufacturingOrderRepository.save(mo);
        return saved;
    }

    @Transactional
    public ManufacturingOrder completeOrder(String id) {
        ManufacturingOrder mo = manufacturingOrderRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Manufacturing order not found: " + id));

        if (!"Confirmed".equals(mo.getStatus()) && !"In Progress".equals(mo.getStatus())) {
            throw new IllegalStateException("Only Confirmed or In Progress orders can be completed.");
        }

        String userId = SecurityUtils.getCurrentUserId();

        // Validate that all work orders are completed before allowing MO completion
        // Accept both "Completed" (set via UI) and "Done" (set via seed/legacy data)
        if (mo.getWorkOrders() != null) {
            for (WorkOrder wo : mo.getWorkOrders()) {
                if (!"Completed".equals(wo.getStatus()) && !"Done".equals(wo.getStatus())) {
                    throw new IllegalStateException("All work orders must be completed before the manufacturing order can be marked as Done.");
                }
            }
        }

        // 1. Consume components
        if (mo.getComponents() != null) {
            for (MoComponent comp : mo.getComponents()) {
                int toConsume = comp.getToConsumeQty();
                if (toConsume > 0) {
                    stockLedgerService.recordMovement(
                            comp.getProductId(),
                            "MFG_CONSUME",
                            toConsume,
                            "MO",
                            mo.getId(),
                            "Consume components for MO completion"
                    );
                    comp.setConsumedQty(comp.getConsumedQty() + toConsume);
                    comp.setToConsumeQty(0);
                }
            }
        }

        // 2. Produce finished product
        stockLedgerService.recordMovement(
                mo.getProductId(),
                "MFG_PRODUCE",
                mo.getQty(),
                "MO",
                mo.getId(),
                "Produce finished product for MO completion"
        );

        // 3. Mark all remaining non-completed work orders as Completed
        if (mo.getWorkOrders() != null) {
            LocalDateTime now = LocalDateTime.now();
            for (WorkOrder wo : mo.getWorkOrders()) {
                if (!"Completed".equals(wo.getStatus()) && !"Done".equals(wo.getStatus())) {
                    if ("Started".equals(wo.getStatus()) && wo.getStartedAt() != null) {
                        long minutes = Duration.between(wo.getStartedAt(), now).toMinutes();
                        wo.setActualDurationMinutes(wo.getActualDurationMinutes() + (int) minutes);
                    }
                    wo.setStatus("Completed");
                    wo.setStartedAt(null);
                    wo.setCompletedAt(now);
                }
            }
        }

        String oldStatus = mo.getStatus();
        mo.setStatus("Done");
        ManufacturingOrder saved = manufacturingOrderRepository.save(mo);

        // Notify admins
        Product productForNotif = productRepository.findById(saved.getProductId()).orElse(null);
        String productName = productForNotif != null ? productForNotif.getName() : saved.getProductId();

        notificationService.notifyUserOrRoles(
                null,
                List.of("admin"),
                "Manufacturing Order Done",
                String.format("Manufacturing Order %s for %s has been completed.", saved.getNumber(), productName),
                "PRODUCT",
                saved.getProductId()
        );

        // Notify sales rep if linked to a Sales Order
        if (saved.getTriggeringSalesOrderId() != null && !saved.getTriggeringSalesOrderId().isEmpty()) {
            salesOrderRepository.findById(saved.getTriggeringSalesOrderId()).ifPresent(so -> {
                String repId = so.getCreatedBy();
                if (repId != null && !repId.isEmpty()) {
                    notificationService.createNotification(
                            repId,
                            "MTO Stock Available",
                            String.format("Production of %s is done for Sales Order %s. Last completed via %s.", productName, so.getNumber(), saved.getNumber()),
                            "PRODUCT",
                            saved.getProductId()
                    );
                }
            });
        }

        auditLogService.logChange(
                userId,
                "ManufacturingOrder",
                saved.getId(),
                "Completed",
                oldStatus,
                String.format("{\"newStatus\": \"%s\", \"productName\": \"%s\", \"qty\": %d}", "Done", productName, saved.getQty())
        );

        return saved;
    }

    @Transactional
    public ManufacturingOrder cancelOrder(String id) {
        ManufacturingOrder mo = manufacturingOrderRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Manufacturing order not found: " + id));

        if ("Done".equals(mo.getStatus()) || "Cancelled".equals(mo.getStatus())) {
            throw new IllegalStateException("Completed or Cancelled orders cannot be cancelled.");
        }

        String userId = SecurityUtils.getCurrentUserId();
        String oldStatus = mo.getStatus();

        // Release reserved stock for components if Confirmed, In Progress, or Waiting for Materials
        if ("Confirmed".equals(mo.getStatus()) || "In Progress".equals(mo.getStatus()) || "Waiting for Materials".equals(mo.getStatus())) {
            if (mo.getComponents() != null) {
                for (MoComponent comp : mo.getComponents()) {
                    // Since it was reserved, we release it
                    stockLedgerService.recordMovement(
                            comp.getProductId(),
                            "MFG_CANCEL",
                            comp.getRequiredQty(),
                            "MO",
                            mo.getId(),
                            "Release reserved stock on Manufacturing Order cancellation"
                    );
                }
            }
        }

        mo.setStatus("Cancelled");
        ManufacturingOrder saved = manufacturingOrderRepository.save(mo);

        auditLogService.logChange(
                userId,
                "ManufacturingOrder",
                saved.getId(),
                "Cancelled",
                oldStatus,
                "Cancelled"
        );

        return saved;
    }
}
