package com.shiv.erp.service;

import com.shiv.erp.model.*;
import com.shiv.erp.repository.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Service
public class ProcurementService {

    private final ProductRepository productRepository;
    private final PurchaseOrderRepository purchaseOrderRepository;
    private final ManufacturingOrderRepository manufacturingOrderRepository;
    private final BoMRepository bomRepository;
    private final AuditLogService auditLogService;
    private final VendorRepository vendorRepository;

    public ProcurementService(ProductRepository productRepository,
                              PurchaseOrderRepository purchaseOrderRepository,
                              ManufacturingOrderRepository manufacturingOrderRepository,
                              BoMRepository bomRepository,
                              @Lazy AuditLogService auditLogService,
                              VendorRepository vendorRepository) {
        this.productRepository = productRepository;
        this.purchaseOrderRepository = purchaseOrderRepository;
        this.manufacturingOrderRepository = manufacturingOrderRepository;
        this.bomRepository = bomRepository;
        this.auditLogService = auditLogService;
        this.vendorRepository = vendorRepository;
    }

    public synchronized void checkAndTriggerProcurement(String productId) {
        Product product = productRepository.findById(productId).orElse(null);
        if (product == null) return;

        // Only MTS products trigger threshold-based automatic replenishment
        if (product.getStrategy() == null || !"MTS".equalsIgnoreCase(product.getStrategy())) {
            return;
        }

        int freeToUse = product.getOnHandQty() - product.getReservedQty();
        int threshold = product.getReorderThreshold();

        if (freeToUse <= threshold) {
            int shortage = threshold - freeToUse;
            if (shortage <= 0) return;

            triggerProcurement(product, shortage, null);
        }
    }

    @Transactional
    public synchronized void triggerProcurement(Product product, int shortage, String triggeringSalesOrderId) {
        if ("Purchase".equalsIgnoreCase(product.getProcurementType())) {
            // Find vendor
            String vendorId = product.getPreferredVendorId();
            if (vendorId == null || vendorId.isEmpty()) {
                List<Vendor> vendors = vendorRepository.findAll();
                if (!vendors.isEmpty()) {
                    vendorId = vendors.get(0).getId();
                } else {
                    vendorId = "v-temp"; // Default fallback
                }
            }

            // Create Auto PO
            String poNumber = generateNextNumber("PO", purchaseOrderRepository.findFirstByOrderByNumberDesc().map(PurchaseOrder::getNumber));
            String poId = "po-" + UUID.randomUUID().toString().substring(0, 8);

            PurchaseOrderLine line = PurchaseOrderLine.builder()
                    .id("pol-" + UUID.randomUUID().toString().substring(0, 8))
                    .purchaseOrderId(poId)
                    .productId(product.getId())
                    .qty(shortage)
                    .unitPrice(product.getCostPrice())
                    .receivedQty(0)
                    .build();

            PurchaseOrder po = PurchaseOrder.builder()
                    .id(poId)
                    .number(poNumber)
                    .vendorId(vendorId)
                    .status("Draft")
                    .createdBy("system") // System action
                    .isAutoGenerated(true)
                    .triggeringSalesOrderId(triggeringSalesOrderId)
                    .lines(List.of(line))
                    .build();

            purchaseOrderRepository.save(po);

            auditLogService.logChange(
                    "system",
                    "PurchaseOrder",
                    poId,
                    "Auto-created",
                    null,
                    String.format("{\"info\": \"Draft auto-generated for %s due to stock shortfall of %d\"}", product.getSku(), shortage)
            );

        } else if ("Manufacturing".equalsIgnoreCase(product.getProcurementType())) {
            // Find linked BoM
            BoM bom = bomRepository.findByProductId(product.getId()).orElse(null);
            if (bom == null) return; // Cannot manufacture without a BoM

            // Create Auto MO
            String moNumber = generateNextNumber("MO", manufacturingOrderRepository.findFirstByOrderByNumberDesc().map(ManufacturingOrder::getNumber));
            String moId = "mo-" + UUID.randomUUID().toString().substring(0, 8);

            // Copy components and operations at creation time
            List<MoComponent> moComponents = new ArrayList<>();
            for (BomComponent bc : bom.getComponents()) {
                moComponents.add(MoComponent.builder()
                        .moId(moId)
                        .productId(bc.getProductId())
                        .requiredQty(bc.getQty() * shortage)
                        .toConsumeQty(bc.getQty() * shortage)
                        .consumedQty(0)
                        .build());
            }

            List<WorkOrder> workOrders = new ArrayList<>();
            for (BomOperation bo : bom.getOperations()) {
                workOrders.add(WorkOrder.builder()
                        .id("wo-" + UUID.randomUUID().toString().substring(0, 8))
                        .moId(moId)
                        .name(bo.getName())
                        .workCenterId(bo.getWorkCenterId())
                        .status("Pending")
                        .expectedDurationMinutes(bo.getDurationMinutes())
                        .actualDurationMinutes(0)
                        .build());
            }

            ManufacturingOrder mo = ManufacturingOrder.builder()
                    .id(moId)
                    .number(moNumber)
                    .productId(product.getId())
                    .qty(shortage)
                    .status("Draft")
                    .assigneeId(null)
                    .isAutoGenerated(true)
                    .triggeringSalesOrderId(triggeringSalesOrderId)
                    .components(moComponents)
                    .workOrders(workOrders)
                    .build();

            manufacturingOrderRepository.save(mo);

            auditLogService.logChange(
                    "system",
                    "ManufacturingOrder",
                    moId,
                    "Auto-created",
                    null,
                    String.format("{\"info\": \"Draft auto-generated for %s due to stock shortfall of %d\"}", product.getSku(), shortage)
            );
        }
    }

    public String generateNextNumber(String prefix, Optional<String> lastNumberOpt) {
        if (!lastNumberOpt.isPresent()) {
            return String.format("%s-%06d", prefix, 1);
        }

        String lastNum = lastNumberOpt.get();
        try {
            String[] parts = lastNum.split("-");
            if (parts.length > 1) {
                String seqStr = parts[parts.length - 1];
                int nextSeq = Integer.parseInt(seqStr) + 1;

                // Reconstruct the prefix parts
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < parts.length - 1; i++) {
                    if (i > 0) sb.append("-");
                    sb.append(parts[i]);
                }

                // Keep the exact same padding length as the last suffix
                String formatStr = "%s-%0" + seqStr.length() + "d";
                return String.format(formatStr, sb.toString(), nextSeq);
            }
        } catch (Exception e) {
            // Fail-safe default
        }
        return String.format("%s-%06d", prefix, 1);
    }
}
