package com.shiv.erp.service;

import com.shiv.erp.model.PurchaseOrder;
import com.shiv.erp.model.PurchaseOrderLine;
import com.shiv.erp.repository.PurchaseOrderRepository;
import com.shiv.erp.utils.SecurityUtils;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.*;

@Service
public class PurchaseOrderService {

    private final PurchaseOrderRepository purchaseOrderRepository;
    private final StockLedgerService stockLedgerService;
    private final ProcurementService procurementService;
    private final AuditLogService auditLogService;

    public PurchaseOrderService(PurchaseOrderRepository purchaseOrderRepository,
                               StockLedgerService stockLedgerService,
                               ProcurementService procurementService,
                               AuditLogService auditLogService) {
        this.purchaseOrderRepository = purchaseOrderRepository;
        this.stockLedgerService = stockLedgerService;
        this.procurementService = procurementService;
        this.auditLogService = auditLogService;
    }

    @Transactional
    public PurchaseOrder createOrder(PurchaseOrder draft) {
        String poId = "po-" + UUID.randomUUID().toString().substring(0, 8);
        String number = procurementService.generateNextNumber("PO", purchaseOrderRepository.findFirstByOrderByNumberDesc().map(PurchaseOrder::getNumber));

        draft.setId(poId);
        draft.setNumber(number);
        draft.setStatus("Draft");
        draft.setCreatedBy(SecurityUtils.getCurrentUserId());
        draft.setIsAutoGenerated(false);

        if (draft.getLines() != null) {
            for (PurchaseOrderLine line : draft.getLines()) {
                line.setId("pol-" + UUID.randomUUID().toString().substring(0, 8));
                line.setPurchaseOrderId(poId);
                line.setReceivedQty(0);
            }
        }

        PurchaseOrder saved = purchaseOrderRepository.save(draft);

        auditLogService.logChange(
                SecurityUtils.getCurrentUserId(),
                "PurchaseOrder",
                saved.getId(),
                "Created",
                null,
                String.format("{\"number\": \"%s\", \"vendorId\": \"%s\"}", saved.getNumber(), saved.getVendorId())
        );

        return saved;
    }

    @Transactional
    public PurchaseOrder confirmOrder(String id) {
        PurchaseOrder po = purchaseOrderRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Purchase order not found: " + id));

        if (!"Draft".equals(po.getStatus())) {
            throw new IllegalStateException("Only Draft purchase orders can be confirmed.");
        }

        if (po.getLines() == null || po.getLines().isEmpty()) {
            throw new IllegalStateException("Purchase order must contain at least one line item.");
        }

        String userId = SecurityUtils.getCurrentUserId();
        po.setStatus("Confirmed");
        PurchaseOrder saved = purchaseOrderRepository.save(po);

        auditLogService.logChange(
                userId,
                "PurchaseOrder",
                saved.getId(),
                "Confirmed",
                "Draft",
                "Confirmed"
        );

        return saved;
    }

    @Transactional
    public PurchaseOrder receiveOrder(String id, Map<String, Integer> receipts) {
        PurchaseOrder po = purchaseOrderRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Purchase order not found: " + id));

        if (!"Confirmed".equals(po.getStatus()) && !"Partially Received".equals(po.getStatus())) {
            throw new IllegalStateException("Goods can only be received for Confirmed or Partially Received purchase orders.");
        }

        String userId = SecurityUtils.getCurrentUserId();
        boolean allFullyReceived = true;

        for (PurchaseOrderLine line : po.getLines()) {
            int toReceive = receipts.getOrDefault(line.getId(), 0);
            if (toReceive <= 0) {
                if (line.getReceivedQty() < line.getQty()) {
                    allFullyReceived = false;
                }
                continue;
            }

            int maxReceivable = line.getQty() - line.getReceivedQty();
            if (toReceive > maxReceivable) {
                throw new IllegalArgumentException(String.format("Receipt quantity %d exceeds remaining order qty %d for line %s", toReceive, maxReceivable, line.getId()));
            }

            // Record receipt movement (this will increase on_hand_qty and check safety stock limits)
            stockLedgerService.executeMovement(
                    line.getProductId(),
                    "PURCHASE_RECEIPT",
                    toReceive,
                    "PO",
                    po.getId(),
                    "Receive stock from Purchase Order"
            );

            // Update line
            line.setReceivedQty(line.getReceivedQty() + toReceive);

            if (line.getReceivedQty() < line.getQty()) {
                allFullyReceived = false;
            }
        }

        String oldStatus = po.getStatus();
        String newStatus = allFullyReceived ? "Fully Received" : "Partially Received";
        po.setStatus(newStatus);
        PurchaseOrder saved = purchaseOrderRepository.save(po);

        auditLogService.logChange(
                userId,
                "PurchaseOrder",
                saved.getId(),
                "Received",
                oldStatus,
                newStatus
        );

        return saved;
    }

    @Transactional
    public PurchaseOrder cancelOrder(String id) {
        PurchaseOrder po = purchaseOrderRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Purchase order not found: " + id));

        if ("Fully Received".equals(po.getStatus()) || "Cancelled".equals(po.getStatus())) {
            throw new IllegalStateException("Fully received or cancelled orders cannot be cancelled.");
        }

        String userId = SecurityUtils.getCurrentUserId();
        String oldStatus = po.getStatus();

        po.setStatus("Cancelled");
        PurchaseOrder saved = purchaseOrderRepository.save(po);

        auditLogService.logChange(
                userId,
                "PurchaseOrder",
                saved.getId(),
                "Cancelled",
                oldStatus,
                "Cancelled"
        );

        return saved;
    }
}
