package com.shiv.erp.service;

import com.shiv.erp.model.PurchaseOrder;
import com.shiv.erp.model.PurchaseOrderLine;
import com.shiv.erp.repository.PurchaseOrderRepository;
import com.shiv.erp.repository.SalesOrderRepository;
import com.shiv.erp.utils.SecurityUtils;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.*;

@Service
public class PurchaseOrderService {

    private final PurchaseOrderRepository purchaseOrderRepository;
    private final StockLedgerService stockLedgerService;
    private final ProcurementService procurementService;
    private final AuditLogService auditLogService;
    private final NotificationService notificationService;
    private final SalesOrderRepository salesOrderRepository;

    public PurchaseOrderService(PurchaseOrderRepository purchaseOrderRepository,
                               StockLedgerService stockLedgerService,
                               ProcurementService procurementService,
                               AuditLogService auditLogService,
                               NotificationService notificationService,
                               SalesOrderRepository salesOrderRepository) {
        this.purchaseOrderRepository = purchaseOrderRepository;
        this.stockLedgerService = stockLedgerService;
        this.procurementService = procurementService;
        this.auditLogService = auditLogService;
        this.notificationService = notificationService;
        this.salesOrderRepository = salesOrderRepository;
    }

    public String normalizeStatus(String status) {
        if (status == null) return "Draft";
        switch (status.toUpperCase()) {
            case "DRAFT": return "Draft";
            case "BOOKED": return "Booked";
            case "CONFIRMED": return "Confirmed";
            case "PARTIALLY_RECEIVED":
            case "PARTIALLY RECEIVED": return "Partially Received";
            case "FULLY_RECEIVED":
            case "FULLY RECEIVED": return "Fully Received";
            case "CANCELLED": return "Cancelled";
            default: return status;
        }
    }

    public List<PurchaseOrder> getFilteredOrders(String status, String vendorId, String dateFrom, String dateTo) {
        List<PurchaseOrder> all = purchaseOrderRepository.findAll();
        all.sort((a, b) -> {
            LocalDateTime da = a.getDate();
            LocalDateTime db = b.getDate();
            if (da == null && db == null) return 0;
            if (da == null) return 1;
            if (db == null) return -1;
            return db.compareTo(da);
        });

        return all.stream().filter(po -> {
            if (status != null && !status.isEmpty()) {
                if (!po.getStatus().equalsIgnoreCase(status) && !normalizeStatus(po.getStatus()).equalsIgnoreCase(normalizeStatus(status))) {
                    return false;
                }
            }
            if (vendorId != null && !vendorId.isEmpty() && !vendorId.equals(po.getVendorId())) {
                return false;
            }
            if (dateFrom != null && !dateFrom.isEmpty()) {
                try {
                    LocalDateTime from = LocalDateTime.parse(dateFrom + "T00:00:00");
                    if (po.getDate() == null || po.getDate().isBefore(from)) return false;
                } catch (Exception e) {
                    // Ignore date parse errors
                }
            }
            if (dateTo != null && !dateTo.isEmpty()) {
                try {
                    LocalDateTime to = LocalDateTime.parse(dateTo + "T23:59:59");
                    if (po.getDate() == null || po.getDate().isAfter(to)) return false;
                } catch (Exception e) {
                    // Ignore date parse errors
                }
            }
            return true;
        }).collect(java.util.stream.Collectors.toList());
    }

    @Transactional
    public PurchaseOrder createOrder(PurchaseOrder draft) {
        String poId = "po-" + UUID.randomUUID().toString().substring(0, 8);
        
        String lastNumber = purchaseOrderRepository.findMaxPoNumber();
        int next = 1;
        if (lastNumber != null) {
            try {
                String clean = lastNumber.replace("PO-", "").replace("-", "");
                next = Integer.parseInt(clean) + 1;
            } catch (Exception e) {
                next = 1;
            }
        }
        String poNumber = String.format("PO-%06d", next);

        draft.setId(poId);
        draft.setNumber(poNumber);
        draft.setStatus("Draft");
        draft.setCreatedBy(SecurityUtils.getCurrentUserId());
        draft.setIsAutoGenerated(false);

        if (draft.getLines() != null) {
            for (PurchaseOrderLine line : draft.getLines()) {
                line.setId("pol-" + UUID.randomUUID().toString().substring(0, 8));
                line.setPurchaseOrderId(poId);
                line.setReceivedQty(0);
            }
        }

        PurchaseOrder saved = purchaseOrderRepository.save(draft);

        auditLogService.logChange(
                SecurityUtils.getCurrentUserId(),
                "PurchaseOrder",
                saved.getId(),
                "Created",
                null,
                String.format("{\"number\": \"%s\", \"vendorId\": \"%s\"}", saved.getNumber(), saved.getVendorId())
        );

        return saved;
    }

    @Transactional
    public PurchaseOrder updateOrder(String id, PurchaseOrder updated) {
        PurchaseOrder po = purchaseOrderRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Purchase order not found: " + id));

        if (!"Draft".equalsIgnoreCase(po.getStatus())) {
            throw new IllegalStateException("Only Draft purchase orders can be updated.");
        }

        po.setVendorId(updated.getVendorId());
        po.setExpectedDeliveryDate(updated.getExpectedDeliveryDate());
        po.setNotes(updated.getNotes());

        if (po.getLines() == null) {
            po.setLines(new ArrayList<>());
        } else {
            po.getLines().clear();
        }

        if (updated.getLines() != null) {
            for (PurchaseOrderLine line : updated.getLines()) {
                line.setId("pol-" + UUID.randomUUID().toString().substring(0, 8));
                line.setPurchaseOrderId(id);
                line.setReceivedQty(0);
                po.getLines().add(line);
            }
        }

        PurchaseOrder saved = purchaseOrderRepository.save(po);

        auditLogService.logChange(
                SecurityUtils.getCurrentUserId(),
                "PurchaseOrder",
                saved.getId(),
                "Updated",
                null,
                "Updated draft fields and lines"
        );

        return saved;
    }

    @Transactional
    public PurchaseOrder bookOrder(String id) {
        PurchaseOrder po = purchaseOrderRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Purchase order not found: " + id));

        if (!"Draft".equalsIgnoreCase(po.getStatus())) {
            throw new IllegalStateException("Only Draft purchase orders can be booked.");
        }

        if (po.getLines() == null || po.getLines().isEmpty()) {
            throw new IllegalStateException("Purchase order must contain at least one line item.");
        }

        po.setStatus("Booked");
        PurchaseOrder saved = purchaseOrderRepository.save(po);

        auditLogService.logChange(
                SecurityUtils.getCurrentUserId(),
                "PurchaseOrder",
                saved.getId(),
                "Booked",
                "Draft",
                "Booked"
        );

        return saved;
    }

    @Transactional
    public PurchaseOrder confirmOrder(String id) {
        PurchaseOrder po = purchaseOrderRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Purchase order not found: " + id));

        if (!"Booked".equalsIgnoreCase(po.getStatus())) {
            throw new IllegalStateException("Only Booked purchase orders can be confirmed.");
        }

        if (po.getLines() == null || po.getLines().isEmpty()) {
            throw new IllegalStateException("Purchase order must contain at least one line item.");
        }

        String userId = SecurityUtils.getCurrentUserId();
        po.setStatus("Confirmed");
        PurchaseOrder saved = purchaseOrderRepository.save(po);

        auditLogService.logChange(
                userId,
                "PurchaseOrder",
                saved.getId(),
                "Confirmed",
                "Booked",
                "Confirmed"
        );

        return saved;
    }

    @Transactional
    public PurchaseOrder receiveOrder(String id, Map<String, Integer> receipts) {
        PurchaseOrder po = purchaseOrderRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Purchase order not found: " + id));

        if (!"Confirmed".equalsIgnoreCase(po.getStatus()) && !"Partially Received".equalsIgnoreCase(po.getStatus())) {
            throw new IllegalStateException("Goods can only be received for Confirmed or Partially Received purchase orders.");
        }

        String userId = SecurityUtils.getCurrentUserId();
        boolean allFullyReceived = true;

        for (PurchaseOrderLine line : po.getLines()) {
            int toReceive = receipts.getOrDefault(line.getId(), 0);
            int maxReceivable = line.getQty() - line.getReceivedQty();
            
            if (toReceive > 0) {
                if (toReceive > maxReceivable) {
                    throw new IllegalArgumentException(String.format("Receipt quantity %d exceeds remaining order qty %d for line %s", toReceive, maxReceivable, line.getId()));
                }

                // Record receipt movement (this will increase on_hand_qty and check safety stock limits)
                stockLedgerService.executeMovement(
                        line.getProductId(),
                        "PURCHASE_RECEIPT",
                        toReceive,
                        "PO",
                        po.getId(),
                        "Receive stock from Purchase Order"
                );

                // Update line
                line.setReceivedQty(line.getReceivedQty() + toReceive);
            }

            if (line.getReceivedQty() < line.getQty()) {
                allFullyReceived = false;
            }
        }

        String oldStatus = po.getStatus();
        String newStatus = allFullyReceived ? "Fully Received" : "Partially Received";
        po.setStatus(newStatus);
        PurchaseOrder saved = purchaseOrderRepository.save(po);

        // Notify sales rep if linked to a Sales Order
        if (saved.getTriggeringSalesOrderId() != null && !saved.getTriggeringSalesOrderId().isEmpty()) {
            salesOrderRepository.findById(saved.getTriggeringSalesOrderId()).ifPresent(so -> {
                String repId = so.getCreatedBy();
                if (repId != null && !repId.isEmpty()) {
                    notificationService.createNotification(
                            repId,
                            "MTO Stock Available",
                            String.format("Shortage resolved for Sales Order %s. Link stock is now received from PO %s.", so.getNumber(), saved.getNumber()),
                            "SALES_ORDER",
                            so.getId()
                    );
                }
            });
        }

        // Notify operations role
        int linesCount = po.getLines().size();
        notificationService.notifyRole(
                "OPERATIONS",
                "PO Received: " + saved.getNumber(),
                "Stock updated for " + linesCount + " product(s)",
                "PURCHASE_ORDER",
                saved.getId()
        );

        auditLogService.logChange(
                userId,
                "PurchaseOrder",
                saved.getId(),
                "Received",
                oldStatus,
                newStatus
        );

        return saved;
    }

    @Transactional
    public PurchaseOrder cancelOrder(String id) {
        PurchaseOrder po = purchaseOrderRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Purchase order not found: " + id));

        if (!"Draft".equalsIgnoreCase(po.getStatus()) && !"Booked".equalsIgnoreCase(po.getStatus())) {
            throw new IllegalStateException("Only Draft or Booked purchase orders can be cancelled.");
        }

        String userId = SecurityUtils.getCurrentUserId();
        String oldStatus = po.getStatus();

        po.setStatus("Cancelled");
        PurchaseOrder saved = purchaseOrderRepository.save(po);

        auditLogService.logChange(
                userId,
                "PurchaseOrder",
                saved.getId(),
                "Cancelled",
                oldStatus,
                "Cancelled"
        );

        return saved;
    }
}
