import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { format } from "date-fns";
import { ChevronLeft, ChevronRight, RefreshCw, Zap, ArrowDown, FileText, CheckCircle2, XCircle, AlertCircle } from "lucide-react";

export const Route = createFileRoute("/_app/automation")({
  head: () => ({ meta: [{ title: "Automation Dashboard — Shiv Furniture Works" }] }),
  component: AutomationPage,
});

const PAGE_SIZE = 20;

interface AutomationEvent {
  id: string;
  ts: string;
  triggerType: string;
  triggerEntityId: string;
  productId: string;
  productSku: string;
  availableQty: number;
  requiredQty: number;
  shortageQty: number;
  actionTaken: string;
  generatedDocId: string;
  generatedDocNumber: string;
  status: string;
  notes: string;
  parentEventId?: string;
}

interface Summary {
  activeShortages: number;
  autoGeneratedPOs: number;
  autoGeneratedMOs: number;
  preventedStockouts: number;
  successRate: number;
}

function ActionBadge({ action }: { action: string }) {
  if (!action) {
    return (
      <span className="inline-flex items-center text-xs px-2 py-0.5 rounded-full font-medium border uppercase tracking-wider bg-red-50 text-red-700 border-red-200">
        FAILED
      </span>
    );
  }
  const lower = action.toLowerCase();
  let cls = "bg-gray-50 text-gray-700 border-gray-200";
  if (lower === "po_created") {
    cls = "bg-blue-50 text-blue-700 border-blue-200";
  } else if (lower === "mo_created") {
    cls = "bg-purple-50 text-purple-700 border-purple-200";
  } else if (lower === "po_updated" || lower === "mo_updated") {
    cls = "bg-amber-50 text-amber-700 border-amber-200";
  }

  const label = action.replace("_", " ");
  return (
    <span className={`inline-flex items-center text-xs px-2 py-0.5 rounded-full font-medium border uppercase tracking-wider ${cls}`}>
      {label}
    </span>
  );
}

function StatusBadge({ status }: { status: string }) {
  let cls = "bg-gray-50 text-gray-700 border-gray-200";
  if (status === "SUCCESS") cls = "bg-green-50 text-green-700 border-green-200";
  else if (status === "FAILED") cls = "bg-red-50 text-red-700 border-red-200";

  return (
    <span className={`inline-flex items-center text-[10px] px-1.5 py-0.5 rounded font-bold border ${cls}`}>
      {status}
    </span>
  );
}

function AutomationPage() {
  const [summary, setSummary] = useState<Summary>({
    activeShortages: 0,
    autoGeneratedPOs: 0,
    autoGeneratedMOs: 0,
    preventedStockouts: 0,
    successRate: 100,
  });

  const [page, setPage] = useState(1);
  const [events, setEvents] = useState<AutomationEvent[]>([]);
  const [totalPages, setTotalPages] = useState(1);
  const [totalElements, setTotalElements] = useState(0);
  const [loading, setLoading] = useState(false);
  const [refreshKey, setRefreshKey] = useState(0);

  // Expanded event state for chain timeline
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [chain, setChain] = useState<AutomationEvent[]>([]);
  const [chainLoading, setChainLoading] = useState(false);

  const fetchSummary = async () => {
    try {
      const token = localStorage.getItem("token");
      const headers: HeadersInit = { "Content-Type": "application/json" };
      if (token) headers["Authorization"] = `Bearer ${token}`;
      const res = await fetch("http://localhost:4000/api/automation/summary", { headers });
      if (res.ok) {
        const data = await res.json();
        setSummary(data);
      }
    } catch (e) {
      console.error(e);
    }
  };

  const fetchEvents = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem("token");
      const headers: HeadersInit = { "Content-Type": "application/json" };
      if (token) headers["Authorization"] = `Bearer ${token}`;
      const res = await fetch(`http://localhost:4000/api/automation/events?page=${page}&size=${PAGE_SIZE}`, { headers });
      if (res.ok) {
        const data = await res.json();
        setEvents(data.content || []);
        setTotalPages(data.totalPages || 1);
        setTotalElements(data.totalElements || 0);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const fetchChain = async (id: string) => {
    setChainLoading(true);
    try {
      const token = localStorage.getItem("token");
      const headers: HeadersInit = { "Content-Type": "application/json" };
      if (token) headers["Authorization"] = `Bearer ${token}`;
      const res = await fetch(`http://localhost:4000/api/automation/events/${id}/chain`, { headers });
      if (res.ok) {
        const data = await res.json();
        setChain(data);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setChainLoading(false);
    }
  };

  useEffect(() => {
    fetchSummary();
  }, [refreshKey]);

  useEffect(() => {
    fetchEvents();
  }, [page, refreshKey]);

  const handleRowClick = (id: string) => {
    if (expandedId === id) {
      setExpandedId(null);
      setChain([]);
    } else {
      setExpandedId(id);
      fetchChain(id);
    }
  };

  const handleRefresh = () => {
    setRefreshKey(p => p + 1);
    setExpandedId(null);
    setChain([]);
  };

  const pageNumbers = useMemo(() => {
    const pages: (number | "...")[] = [];
    if (totalPages <= 7) {
      for (let i = 1; i <= totalPages; i++) pages.push(i);
    } else {
      pages.push(1);
      if (page > 3) pages.push("...");
      const start = Math.max(2, page - 1);
      const end = Math.min(totalPages - 1, page + 1);
      for (let i = start; i <= end; i++) pages.push(i);
      if (page < totalPages - 2) pages.push("...");
      pages.push(totalPages);
    }
    return pages;
  }, [totalPages, page]);

  return (
    <div className="space-y-6">
      {/* Header bar */}
      <div className="flex items-center justify-between">
        <div>
          <p className="text-sm text-gray-500">Real-time procurement shortage detection and auto-replenishment tracking.</p>
        </div>
        <button
          onClick={handleRefresh}
          className="inline-flex h-9 items-center gap-2 rounded-md border border-gray-200 bg-white px-3 text-sm font-medium text-gray-600 hover:bg-gray-50 transition-colors"
        >
          <RefreshCw className="h-4 w-4" />
          Refresh Dashboard
        </button>
      </div>

      {/* SECTION 1: KPI Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
        <KpiCard
          label="Active Shortages"
          value={summary.activeShortages}
          sub="Products below reorder threshold"
          borderColor="#ef4444"
        />
        <KpiCard
          label="Auto Generated POs"
          value={summary.autoGeneratedPOs}
          sub="Draft Purchase Orders"
          borderColor="#7C5C3E"
        />
        <KpiCard
          label="Auto Generated MOs"
          value={summary.autoGeneratedMOs}
          sub="Draft Manufacturing Orders"
          borderColor="#7C5C3E"
        />
        <KpiCard
          label="Prevented Stockouts"
          value={summary.preventedStockouts}
          sub="Successful auto-interventions"
          borderColor="#22c55e"
        />
        <KpiCard
          label="Success Rate"
          value={`${summary.successRate}%`}
          sub="Resolution accuracy"
          borderColor="#C76B3F"
        />
      </div>

      {/* SECTION 2: Automation Activity & Chain Timeline */}
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        {/* Left 2 cols: Activity Table */}
        <div className="xl:col-span-2 rounded-lg border border-gray-200 bg-white shadow-sm overflow-hidden">
          <div className="border-b border-gray-200 px-4 py-4 flex items-center justify-between bg-gray-50/50">
            <h3 className="font-serif text-base font-semibold text-[#2B2622]">Automation Decisions</h3>
            <span className="text-xs text-gray-500 font-medium">Showing {events.length} of {totalElements} decisions</span>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-gray-200 bg-gray-50 text-[11px] font-bold uppercase tracking-wider text-gray-500">
                  <th className="px-4 py-3">Timestamp</th>
                  <th className="px-4 py-3">Product SKU</th>
                  <th className="px-4 py-3 text-right">Available</th>
                  <th className="px-4 py-3 text-right">Required</th>
                  <th className="px-4 py-3 text-right">Shortage</th>
                  <th className="px-4 py-3">Action Taken</th>
                  <th className="px-4 py-3">Document</th>
                  <th className="px-4 py-3">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 text-xs text-gray-700">
                {loading ? (
                  <tr>
                    <td colSpan={8} className="py-10 text-center text-gray-400">Loading automation logs...</td>
                  </tr>
                ) : events.length === 0 ? (
                  <tr>
                    <td colSpan={8} className="py-10 text-center text-gray-400">No automation events recorded yet.</td>
                  </tr>
                ) : (
                  events.map((e) => {
                    const isSelected = expandedId === e.id;
                    return (
                      <tr
                        key={e.id}
                        onClick={() => handleRowClick(e.id)}
                        className={`hover:bg-gray-50 cursor-pointer transition-colors ${
                          isSelected ? "bg-[#FAF8F5] border-l-2 border-l-[#C76B3F]" : ""
                        }`}
                      >
                        <td className="px-4 py-3 whitespace-nowrap text-gray-500">
                          {e.ts ? format(new Date(e.ts), "dd MMM yyyy HH:mm:ss") : "N/A"}
                        </td>
                        <td className="px-4 py-3 font-medium text-gray-900">{e.productSku}</td>
                        <td className="px-4 py-3 text-right font-medium text-gray-600">{e.availableQty}</td>
                        <td className="px-4 py-3 text-right font-medium text-gray-600">{e.requiredQty}</td>
                        <td className="px-4 py-3 text-right font-semibold text-red-600">{e.shortageQty}</td>
                        <td className="px-4 py-3">
                          <ActionBadge action={e.actionTaken} />
                        </td>
                        <td className="px-4 py-3">
                          {e.generatedDocId ? (
                            <Link
                              to={(e.actionTaken && e.actionTaken.includes("PO")) ? "/purchase/$id" : "/manufacturing/$id"}
                              params={{ id: e.generatedDocId }}
                              className="text-[#C76B3F] hover:underline font-medium inline-flex items-center gap-1"
                              onClick={(event) => event.stopPropagation()}
                            >
                              <FileText className="h-3 w-3" />
                              {e.generatedDocNumber}
                            </Link>
                          ) : (
                            <span className="text-gray-400">–</span>
                          )}
                        </td>
                        <td className="px-4 py-3">
                          <StatusBadge status={e.status} />
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          {totalPages > 1 && (
            <div className="border-t border-gray-200 px-4 py-3.5 flex items-center justify-between">
              <span className="text-xs text-gray-500">
                Showing Page {page} of {totalPages}
              </span>
              <div className="flex items-center gap-1">
                <button
                  disabled={page <= 1}
                  onClick={() => setPage(p => Math.max(1, p - 1))}
                  className="inline-flex h-8 w-8 items-center justify-center rounded border border-gray-200 bg-white text-gray-600 hover:bg-gray-50 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
                >
                  <ChevronLeft className="h-4 w-4" />
                </button>
                {pageNumbers.map((pn, idx) =>
                  pn === "..." ? (
                    <span key={`dots-${idx}`} className="px-2 text-gray-400 text-xs">...</span>
                  ) : (
                    <button
                      key={pn}
                      onClick={() => setPage(pn as number)}
                      className={`inline-flex h-8 w-8 items-center justify-center rounded text-xs font-semibold transition-colors ${
                        pn === page
                          ? "bg-[#7C5C3E] text-white"
                          : "border border-gray-200 text-gray-600 bg-white hover:bg-gray-50"
                      }`}
                    >
                      {pn}
                    </button>
                  )
                )}
                <button
                  disabled={page >= totalPages}
                  onClick={() => setPage(p => Math.min(totalPages, p + 1))}
                  className="inline-flex h-8 w-8 items-center justify-center rounded border border-gray-200 bg-white text-gray-600 hover:bg-gray-50 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
                >
                  <ChevronRight className="h-4 w-4" />
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Right col: Chain Timeline */}
        <div className="rounded-lg border border-gray-200 bg-white shadow-sm overflow-hidden flex flex-col">
          <div className="border-b border-gray-200 px-4 py-4 bg-gray-50/50">
            <h3 className="font-serif text-base font-semibold text-[#2B2622] flex items-center gap-1.5">
              <Zap className="h-4 w-4 text-[#C76B3F]" />
              Automation Timeline Chain
            </h3>
          </div>

          <div className="flex-1 p-4 overflow-y-auto max-h-[600px]">
            {!expandedId ? (
              <div className="h-full flex flex-col items-center justify-center text-center py-20 text-gray-400">
                <AlertCircle className="h-8 w-8 text-gray-300 mb-2" />
                <p className="text-xs font-medium">Select any automation decision to view its complete resolution tree chain.</p>
              </div>
            ) : chainLoading ? (
              <div className="py-10 text-center text-xs text-gray-400 animate-pulse">Loading chain details...</div>
            ) : chain.length === 0 ? (
              <div className="py-10 text-center text-xs text-gray-400">No timeline data available for this decision.</div>
            ) : (
              <div className="relative border-l border-gray-200 ml-3 pl-6 space-y-6">
                {chain.map((item, index) => {
                  const isLast = index === chain.length - 1;
                  const isSuccess = item.status === "SUCCESS";
                  const isMo = item.actionTaken && item.actionTaken.includes("MO");
                  const isPo = item.actionTaken && item.actionTaken.includes("PO");

                  return (
                    <div key={item.id} className="relative">
                      {/* Circle indicator on line */}
                      <span className={`absolute -left-[31px] top-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-white ring-2 ${
                        isSuccess ? "ring-green-500 text-green-500" : "ring-red-500 text-red-500"
                      }`}>
                        {isSuccess ? (
                          <CheckCircle2 className="h-3.5 w-3.5 fill-current" />
                        ) : (
                          <XCircle className="h-3.5 w-3.5 fill-current" />
                        )}
                      </span>

                      {/* Timeline Node Info Card */}
                      <div className="bg-[#FAF8F5] rounded-lg border border-gray-150 p-3 text-xs space-y-1.5">
                        <div className="flex items-center justify-between">
                          <span className="font-bold text-[#2B2622]">{item.productSku}</span>
                          <span className="text-[10px] text-gray-400">
                            {item.ts ? format(new Date(item.ts), "HH:mm:ss") : ""}
                          </span>
                        </div>

                        <div className="text-[11px] text-gray-600 leading-normal">
                          Triggered by <span className="font-medium text-gray-800">{item.triggerType}</span> 
                          {item.triggerEntityId ? ` (${item.triggerEntityId})` : ""}
                        </div>

                        <div className="flex flex-wrap gap-2 pt-1 border-t border-gray-100 mt-2">
                          <div className="text-[10px] text-gray-500">
                            Shortage: <span className="font-semibold text-red-600">{item.shortageQty}</span>
                          </div>
                          <div className="text-[10px] text-gray-500">
                            Available: <span className="font-semibold text-gray-700">{item.availableQty}</span>
                          </div>
                        </div>

                        <div className="pt-2 flex items-center justify-between gap-2">
                          <ActionBadge action={item.actionTaken} />
                          {item.generatedDocId && (
                            <Link
                              to={isPo ? "/purchase/$id" : "/manufacturing/$id"}
                              params={{ id: item.generatedDocId }}
                              className="text-[#C76B3F] hover:underline font-bold text-[10px] flex items-center gap-0.5"
                            >
                              {item.generatedDocNumber} →
                            </Link>
                          )}
                        </div>

                        <p className="text-[10px] text-gray-400 italic pt-1 border-t border-gray-50/50 mt-1">
                          {item.notes}
                        </p>
                      </div>

                      {/* Direction Arrow between timeline entries */}
                      {!isLast && (
                        <div className="absolute -left-[27px] top-[48px] h-6 flex items-center justify-center">
                          <ArrowDown className="h-3.5 w-3.5 text-gray-300" />
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

/* KpiCard Subcomponent */
function KpiCard({ label, value, sub, borderColor }: { label: string; value: number | string; sub: string; borderColor: string }) {
  return (
    <div
      className="rounded-lg border border-gray-200 bg-white p-4 border-l-4 shadow-sm"
      style={{ borderLeftColor: borderColor }}
    >
      <div className="text-xs font-semibold uppercase tracking-wider text-gray-400">{label}</div>
      <div className="mt-1.5 text-2xl font-bold text-[#2B2622]">{value}</div>
      <div className="mt-1 text-[11px] text-gray-400 leading-tight">{sub}</div>
    </div>
  );
}
