package com.shiv.erp.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "manufacturing_orders")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ManufacturingOrder {
    @Id
    @Column(length = 50)
    private String id;

    @Column(nullable = false, unique = true, length = 100)
    private String number;

    @Column(name = "product_id", length = 50, nullable = false)
    private String productId;

    @Column(nullable = false)
    private Integer qty;

    @Column(nullable = false, length = 50)
    private String status; // Draft, Confirmed, In Progress, Done, Cancelled

    @Column(name = "assignee_id", length = 36)
    private String assigneeId;

    @Column(name = "date")
    private LocalDateTime date;

    @PrePersist
    protected void onCreate() {
        if (this.date == null) {
            this.date = LocalDateTime.now();
        }
    }

    @Column(name = "is_auto_generated")
    @Builder.Default
    private Boolean isAutoGenerated = false;

    @Column(name = "triggering_sales_order_id", length = 50)
    private String triggeringSalesOrderId;

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @JoinColumn(name = "mo_id")
    private List<MoComponent> components;

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @JoinColumn(name = "mo_id")
    private List<WorkOrder> workOrders;

    @org.hibernate.annotations.UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @Transient
    private List<ShortageTicket> shortageTickets;
}
