package com.shiv.erp.repository;

import com.shiv.erp.model.ManufacturingOrder;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import java.util.List;
import java.util.Optional;

public interface ManufacturingOrderRepository extends JpaRepository<ManufacturingOrder, String> {
    Optional<ManufacturingOrder> findFirstByOrderByNumberDesc();

    @Query("SELECT mo FROM ManufacturingOrder mo WHERE mo.productId = :productId AND mo.status IN ('Draft', 'Confirmed', 'In Progress')")
    List<ManufacturingOrder> findActiveMOsByProduct(@Param("productId") String productId);

    @Query("SELECT DISTINCT mo FROM ManufacturingOrder mo JOIN mo.components c WHERE mo.status = 'Waiting for Materials' AND c.productId = :productId")
    List<ManufacturingOrder> findWaitingMOsByComponentProduct(@Param("productId") String productId);

    long countByIsAutoGeneratedTrue();
}
