package com.shiv.erp.repository;

import com.shiv.erp.model.PurchaseOrder;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import java.util.List;
import java.util.Optional;

public interface PurchaseOrderRepository extends JpaRepository<PurchaseOrder, String> {
    Optional<PurchaseOrder> findFirstByOrderByNumberDesc();

    @Query("SELECT MAX(po.number) FROM PurchaseOrder po")
    String findMaxPoNumber();

    @Query("SELECT po FROM PurchaseOrder po JOIN po.lines l WHERE l.productId = :productId AND po.status IN ('Draft', 'Booked', 'Confirmed')")
    List<PurchaseOrder> findActivePOsByProduct(@Param("productId") String productId);

    long countByIsAutoGeneratedTrue();

    java.util.List<PurchaseOrder> findAllByOrderByUpdatedAtDesc();
}
